### ISSUE TITLE
Avoiding conflict between the CSS talks

### ISSUE THREAD

**Issue by benlk** [CWDG/semester-plans#3]
@egladman 

We've got three talks coming up: 

| Date | Talk | Exercise | Speaker |
| --- | --- | --- | --- |
| 2015-09-15 | CSS - Intro to CSS. Colors, borders, etc. |  | Ben Keith |
| 2015-09-22 | CSS - Positioning. | [Do You Know the DOM?](https://github.com/CWDG/DoYouKnowTheDOM) | ??? |
| 2015-09-29 | CSS - Advanced CSS and preprocessors. | [Do You Know the DOM2](https://github.com/CWDG/DoYouKnowTheDom2) | Eli Gladman |

What should each talk cover?

**Comment by egladman** [comment]
the advanced talk is going to cover css pre-processors, pseudo elements, and grid systems

**Comment by benlk** [comment]
Grid systems seems like it would be under positioning?

I proprose breaking it roughly this way:

CSS - Intro
- what is a CSS file
- how is it loaded
- how do CSS rules map to HTML elements
- what can you do with it?
  - text decoration, sizes, colors
  - overview of block vs inline vs inline-block
  - borders, etc

CSS - Positioning
- static/relative/absolute/fixed/sticky
- applying widths, heights to floats
- grids
- media queries

CSS - Advanced CSS and preprocessors
- animations
- pseudo elements
- preprocessors
- mixins, etc

**Comment by egladman** [comment]
media queries should be under advanced.

**Comment by benlk** [comment]
## CSS - Intro
- what is a CSS file
  - why is it a separate file
  - separation of concerns - don't use church/state metaphor
  - don't use inline styles
- how is it loaded
- how do CSS rules map to HTML elements
- what can you do with it?
  - text decoration, sizes, colors
  - overview of block vs inline vs inline-block
  - borders, etc
- Where you can go from here
  - codecademy
  - MDN, NOT W3Schools
  - codepen

All of that is in pixels

## CSS - Intermediate
- units
- :hover, :active,
- static/relative/absolute/fixed/sticky
- applying widths, heights to floats
- grids
- Approaches to web design
  - responsive
  - mobile-first and progressive enhancement
- media queries
- z-indexes
- Where you can go from here
  - Responsive Web Design, by Ethan Marcotte
  - MDN
  - http://caniuse.com/

## CSS - Advanced CSS and preprocessors
- Using other people's CSS
- animations
- pseudo elements
- filters
- transformations
- browser prefixes
- preprocessors
- mixins, etc
- Where you can go from here
  - MDN
  - StackOverflow

**Comment by benlk** [comment]
And @J3RN approved this layout. I'll take Intro and Intermediate.

**Comment by egladman** [comment]
Sounds good.

**Comment by J3RN** [comment]
I'm going to update the file accordingly, and will close this issue. Thank you guys for your contribution! :sparkles:

**Comment by benlk** [comment]
Is there a place you want me to put the slide deck/demo page when it's mostly-complete?

**Comment by egladman** [comment]
@benlk add z-indexs to your talk

**Comment by J3RN** [comment]
@benlk That depends. If you want it to be publicly accessible to members, GitHub is a good place (unless it's in like MS PowerPoint form or something). If you just want me to review it, you can email it to me.

**Comment by benlk** [comment]
@J3RN Oh, I definitely want it to be accessible to people. But is there a club repo where you'll be keeping past talks, or will the club just keep a set of links to talks hosted elsewhere?

**Comment by J3RN** [comment]
It would be cool if we could set it up so that the list of talks in this file links to where each talk is hosted, if applicable. So, a link would be fine.

**Comment by J3RN** [comment]
As a follow-up, you should be able to click on the talks we've already had this semester and be taken to information about them (kinda, in the case of my talk. I'll add a README).

**Comment by egladman** [comment]
@benlk with regards to your presentation file format: i use [cleaver](https://github.com/jdan/cleaver). it compiles static html presentations from markdown. The main benefit would have to be the ability to use version control.

**Comment by benlk** [comment]
Do either of you have an opinion on where ::psedudo-element fall vs :pseudo-class selectors? Or are pseudo-classes in "Advanced" in addition to the pseudo-elements already listed there?

**Comment by egladman** [comment]
@benlk I think it would make the most sense to have everything pseudo related discussed in the advanced talk

**Comment by J3RN** [comment]
I'm in agreement with Eli here.

**Comment by benlk** [comment]
Sounds good.
